defmodule Cheer.Completion do
  @moduledoc """
  Shell completion script generation for bash, zsh, and fish.

  Generates completion scripts from the command tree metadata.

  ## Usage

      # Generate and print to stdout
      Cheer.Completion.generate(MyApp.CLI.Root, :bash, prog: "my-app")
      Cheer.Completion.generate(MyApp.CLI.Root, :zsh, prog: "my-app")
      Cheer.Completion.generate(MyApp.CLI.Root, :fish, prog: "my-app")
  """

  @doc """
  Generate a shell completion script for the given command tree.

  Options:
    * `:prog` - program name (required)
  """
  @spec generate(module(), :bash | :zsh | :fish, keyword()) :: String.t()
  def generate(root, shell, opts \\ []) do
    prog = Keyword.fetch!(opts, :prog)
    tree = Cheer.tree(root)

    case shell do
      :bash -> generate_bash(tree, prog)
      :zsh -> generate_zsh(tree, prog)
      :fish -> generate_fish(tree, prog)
    end
  end

  # -- Bash --

  defp generate_bash(tree, prog) do
    functions = bash_functions(tree, prog, [prog])

    """
    # Bash completion for #{prog}
    # Generated by Cheer/Cheer

    #{functions}
    complete -F _#{safe_name(prog)} #{prog}
    """
  end

  defp bash_functions(tree, prog, path) do
    fname = "_#{safe_name(Enum.join(path, "_"))}"
    subcommand_names = Enum.map(tree.subcommands, & &1.name)
    option_flags = Enum.flat_map(tree.options, &option_completions/1)
    all_words = subcommand_names ++ option_flags ++ ["--help"]

    func = """
    #{fname}() {
      local cur="${COMP_WORDS[COMP_CWORD]}"
      COMPREPLY=($(compgen -W "#{Enum.join(all_words, " ")}" -- "$cur"))
    }
    """

    child_funcs =
      Enum.map_join(tree.subcommands, "\n", fn sub ->
        bash_functions(sub, prog, path ++ [sub.name])
      end)

    func <> child_funcs
  end

  # -- Zsh --

  defp generate_zsh(tree, prog) do
    subcmds = collect_subcommands(tree, [])

    subcommand_cases =
      Enum.map_join(subcmds, "\n    ", fn {path, sub_tree} ->
        cmd_name = Enum.join(path, "_")
        opts = Enum.map_join(sub_tree.options, " ", &zsh_option_spec/1)
        args = if sub_tree.subcommands != [], do: ":command:->command", else: ""
        "'#{cmd_name}') _arguments #{opts} #{args} ;;"
      end)

    subcommand_names =
      tree.subcommands
      |> Enum.map_join(" ", fn s -> "'#{s.name}:#{escape_zsh(s.about)}'" end)

    top_opts = Enum.map_join(tree.options, " ", &zsh_option_spec/1)

    """
    #compdef #{prog}
    # Zsh completion for #{prog}
    # Generated by Cheer/Cheer

    _#{safe_name(prog)}() {
      local -a commands
      commands=(#{subcommand_names})

      _arguments \\
        #{top_opts} \\
        '1:command:->command' \\
        '*::arg:->args'

      case $state in
        command)
          _describe 'command' commands
          ;;
        args)
          case $words[1] in
            #{subcommand_cases}
          esac
          ;;
      esac
    }

    _#{safe_name(prog)}
    """
  end

  defp zsh_option_spec({name, opts}) do
    help = Keyword.get(opts, :help, "") |> escape_zsh()
    "'--#{name}[#{help}]'"
  end

  defp escape_zsh(str), do: String.replace(str, "'", "'\\''")

  # -- Fish --

  defp generate_fish(tree, prog) do
    lines = fish_completions(tree, prog, [])
    Enum.join(["# Fish completion for #{prog}", "# Generated by Cheer/Cheer", "" | lines], "\n")
  end

  defp fish_completions(tree, prog, parent_path) do
    condition =
      if parent_path == [] do
        "__fish_use_subcommand"
      else
        "__fish_seen_subcommand_from #{List.last(parent_path)}"
      end

    sub_lines =
      Enum.map(tree.subcommands, fn sub ->
        "complete -c #{prog} -n '#{condition}' -a '#{sub.name}' -d '#{escape_fish(sub.about)}'"
      end)

    opt_lines =
      Enum.map(tree.options, fn {name, opts} ->
        help = Keyword.get(opts, :help, "") |> escape_fish()
        short = Keyword.get(opts, :short)
        short_flag = if short, do: " -s #{short}", else: ""
        "complete -c #{prog} -n '#{condition}' -l #{name}#{short_flag} -d '#{help}'"
      end)

    child_lines =
      Enum.flat_map(tree.subcommands, fn sub ->
        fish_completions(sub, prog, parent_path ++ [sub.name])
      end)

    sub_lines ++ opt_lines ++ child_lines
  end

  defp escape_fish(str), do: String.replace(str, "'", "\\'")

  # -- Helpers --

  defp option_completions({name, opts}) do
    flags = ["--#{name}"]
    flags = if Keyword.get(opts, :type) == :boolean, do: flags ++ ["--no-#{name}"], else: flags
    short = Keyword.get(opts, :short)
    if short, do: flags ++ ["-#{short}"], else: flags
  end

  defp collect_subcommands(tree, path) do
    current = {path ++ [tree.name], tree}

    children =
      Enum.flat_map(tree.subcommands, fn sub ->
        collect_subcommands(sub, path ++ [tree.name])
      end)

    [current | children]
  end

  defp safe_name(str) do
    str |> String.replace(~r/[^a-zA-Z0-9]/, "_")
  end
end
