defmodule Cheer.Completion do
  @moduledoc """
  Shell completion script generation for bash, zsh, fish, and PowerShell.

  Generates completion scripts from the command tree metadata.

  ## Usage

      # Generate and print to stdout
      Cheer.Completion.generate(MyApp.CLI.Root, :bash, prog: "my-app")
      Cheer.Completion.generate(MyApp.CLI.Root, :zsh, prog: "my-app")
      Cheer.Completion.generate(MyApp.CLI.Root, :fish, prog: "my-app")
      Cheer.Completion.generate(MyApp.CLI.Root, :powershell, prog: "my-app")
  """

  @doc """
  Generate a shell completion script for the given command tree.

  Options:
    * `:prog` - program name (required)
  """
  @spec generate(module(), :bash | :zsh | :fish | :powershell, keyword()) :: String.t()
  def generate(root, shell, opts \\ []) do
    prog = Keyword.fetch!(opts, :prog)
    tree = Cheer.tree(root)

    case shell do
      :bash -> generate_bash(tree, prog)
      :zsh -> generate_zsh(tree, prog)
      :fish -> generate_fish(tree, prog)
      :powershell -> generate_powershell(tree, prog)
    end
  end

  # -- Bash --

  defp generate_bash(tree, prog) do
    functions = bash_functions(tree, prog, [prog])

    """
    # Bash completion for #{prog}
    # Generated by Cheer/Cheer

    #{functions}
    complete -F _#{safe_name(prog)} #{prog}
    """
  end

  defp bash_functions(tree, prog, path) do
    fname = "_#{safe_name(Enum.join(path, "_"))}"
    subcommand_names = Enum.map(tree.subcommands, & &1.name)
    option_flags = Enum.flat_map(tree.options, &option_completions/1)
    all_words = subcommand_names ++ option_flags ++ ["--help"]

    func = """
    #{fname}() {
      local cur="${COMP_WORDS[COMP_CWORD]}"
      COMPREPLY=($(compgen -W "#{Enum.join(all_words, " ")}" -- "$cur"))
    }
    """

    child_funcs =
      Enum.map_join(tree.subcommands, "\n", fn sub ->
        bash_functions(sub, prog, path ++ [sub.name])
      end)

    func <> child_funcs
  end

  # -- Zsh --

  defp generate_zsh(tree, prog) do
    subcmds = collect_subcommands(tree, [])

    subcommand_cases =
      Enum.map_join(subcmds, "\n    ", fn {path, sub_tree} ->
        cmd_name = Enum.join(path, "_")
        opts = Enum.map_join(sub_tree.options, " ", &zsh_option_spec/1)
        args = if sub_tree.subcommands != [], do: ":command:->command", else: ""
        "'#{cmd_name}') _arguments #{opts} #{args} ;;"
      end)

    subcommand_names =
      tree.subcommands
      |> Enum.map_join(" ", fn s -> "'#{s.name}:#{escape_zsh(s.about)}'" end)

    top_opts = Enum.map_join(tree.options, " ", &zsh_option_spec/1)

    """
    #compdef #{prog}
    # Zsh completion for #{prog}
    # Generated by Cheer/Cheer

    _#{safe_name(prog)}() {
      local -a commands
      commands=(#{subcommand_names})

      _arguments \\
        #{top_opts} \\
        '1:command:->command' \\
        '*::arg:->args'

      case $state in
        command)
          _describe 'command' commands
          ;;
        args)
          case $words[1] in
            #{subcommand_cases}
          esac
          ;;
      esac
    }

    _#{safe_name(prog)}
    """
  end

  defp zsh_option_spec({name, opts}) do
    help = Keyword.get(opts, :help, "") |> escape_zsh()
    "'--#{name}[#{help}]'"
  end

  defp escape_zsh(str), do: String.replace(str, "'", "'\\''")

  # -- Fish --

  defp generate_fish(tree, prog) do
    lines = fish_completions(tree, prog, [])
    Enum.join(["# Fish completion for #{prog}", "# Generated by Cheer/Cheer", "" | lines], "\n")
  end

  defp fish_completions(tree, prog, parent_path) do
    condition =
      if parent_path == [] do
        "__fish_use_subcommand"
      else
        "__fish_seen_subcommand_from #{List.last(parent_path)}"
      end

    sub_lines =
      Enum.map(tree.subcommands, fn sub ->
        "complete -c #{prog} -n '#{condition}' -a '#{sub.name}' -d '#{escape_fish(sub.about)}'"
      end)

    opt_lines =
      Enum.map(tree.options, fn {name, opts} ->
        help = Keyword.get(opts, :help, "") |> escape_fish()
        short = Keyword.get(opts, :short)
        short_flag = if short, do: " -s #{short}", else: ""
        "complete -c #{prog} -n '#{condition}' -l #{name}#{short_flag} -d '#{help}'"
      end)

    child_lines =
      Enum.flat_map(tree.subcommands, fn sub ->
        fish_completions(sub, prog, parent_path ++ [sub.name])
      end)

    sub_lines ++ opt_lines ++ child_lines
  end

  defp escape_fish(str), do: String.replace(str, "'", "\\'")

  # -- PowerShell --

  defp generate_powershell(tree, prog) do
    branches =
      tree
      |> collect_subcommands([])
      |> Enum.map_join("\n", fn {path, sub_tree} ->
        powershell_branch(path, sub_tree, prog)
      end)

    """
    using namespace System.Management.Automation
    using namespace System.Management.Automation.Language

    # PowerShell completion for #{prog}
    # Generated by Cheer

    Register-ArgumentCompleter -Native -CommandName '#{prog}' -ScriptBlock {
        param($wordToComplete, $commandAst, $cursorPosition)

        $commandElements = $commandAst.CommandElements
        $command = @(
            '#{prog}'
            for ($i = 1; $i -lt $commandElements.Count; $i++) {
                $element = $commandElements[$i]
                if ($element -isnot [StringConstantExpressionAst] -or
                    $element.StringConstantType -ne [StringConstantType]::BareWord -or
                    $element.Value.StartsWith('-') -or
                    $element.Value -eq $wordToComplete) {
                    break
                }
                $element.Value
            }) -join ';'

        $completions = @(switch ($command) {
    #{branches}
        })

        $completions.Where{ $_.CompletionText -like "$wordToComplete*" } |
            Sort-Object -Property ListItemText
    }
    """
  end

  defp powershell_branch(path, sub_tree, prog) do
    # Top of tree has path [prog]; nested subs have [prog, sub, ...].
    # Keys are the `;`-joined path, matching what the ScriptBlock builds at runtime.
    key = path |> List.replace_at(0, prog) |> Enum.join(";")

    entries =
      Enum.map(sub_tree.options, &powershell_option_entry/1) ++
        Enum.map(sub_tree.subcommands, &powershell_subcommand_entry/1) ++
        [powershell_help_entry()]

    """
            '#{key}' {
    #{Enum.map_join(entries, "\n", &"            #{&1}")}
                break
            }\
    """
  end

  defp powershell_option_entry({name, opts}) do
    flag = "--#{flag_name(name)}"
    help = opts |> Keyword.get(:help, "") |> escape_powershell()
    tooltip = if help == "", do: flag, else: help
    powershell_result(flag, flag, "ParameterName", tooltip)
  end

  defp powershell_subcommand_entry(sub) do
    about = sub.about |> to_string() |> escape_powershell()
    tooltip = if about == "", do: sub.name, else: about
    powershell_result(sub.name, sub.name, "ParameterValue", tooltip)
  end

  defp powershell_help_entry do
    powershell_result("--help", "--help", "ParameterName", "Print help")
  end

  defp powershell_result(completion, list_item, type, tooltip) do
    "[CompletionResult]::new('#{completion}', '#{list_item}', [CompletionResultType]::#{type}, '#{tooltip}')"
  end

  defp escape_powershell(str), do: String.replace(to_string(str), "'", "''")

  # -- Helpers --

  defp option_completions({name, opts}) do
    flags = ["--#{name}"]
    flags = if Keyword.get(opts, :type) == :boolean, do: flags ++ ["--no-#{name}"], else: flags
    short = Keyword.get(opts, :short)
    if short, do: flags ++ ["-#{short}"], else: flags
  end

  defp collect_subcommands(tree, path) do
    current = {path ++ [tree.name], tree}

    children =
      Enum.flat_map(tree.subcommands, fn sub ->
        collect_subcommands(sub, path ++ [tree.name])
      end)

    [current | children]
  end

  defp safe_name(str) do
    str |> String.replace(~r/[^a-zA-Z0-9]/, "_")
  end

  # Atom option names become kebab-case flags to match what the parser accepts
  # (see `Cheer.Help.flag_from/1`). Used by the PowerShell generator; the other
  # generators have a pre-existing underscore/hyphen inconsistency tracked separately.
  defp flag_name(name) when is_atom(name), do: name |> Atom.to_string() |> flag_name()
  defp flag_name(name) when is_binary(name), do: String.replace(name, "_", "-")
end
